### ISSUE TITLE
Doesn't update config properly

### ISSUE THREAD

**Issue by JimLittle8** [BackTrak/DependencyFixup#3]
What you did is brilliant--however, the program doesn't properly update the config file. It cites the same Old version as it does New, so there is effectively no binding redirect... At least your program outputs the list of detected issues so we can go in manually and update the config file ourselves.

**Comment by BackTrak** [comment]
Hi Jim, could you please supply the application that you were trying to analyze? I have used the application frequently and I have not seen this issue.
